# Generated by Django 4.2.1 on 2023-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='sub_menu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
