# Generated by Django 4.2.1 on 2023-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Media Prabhari', 'media prabhari'), ('Counselor', 'counselor'), ('Citizen', 'citizen'), ('Mayor', 'mayor')], max_length=120, null=True),
        ),
    ]
