# Generated by Django 4.2.1 on 2023-05-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_pages_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='url',
        ),
        migrations.AddField(
            model_name='navbar',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='urls',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
