# Generated by Django 4.2.1 on 2023-05-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_navbar_url_navbar_page_page_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='core.page'),
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='sub_menu',
        ),
        migrations.AddField(
            model_name='navbar',
            name='sub_menu',
            field=models.ManyToManyField(related_name='sub_menu', to='core.page'),
        ),
    ]
