# Generated by Django 4.2.1 on 2023-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_navbar_page_remove_navbar_sub_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='sub_menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_menu', to='core.page'),
        ),
    ]
