# Generated by Django 4.2.1 on 2023-06-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_author_title_remove_author_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='on_home_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
