# Generated by Django 4.2.1 on 2023-06-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gallery_on_home_slide_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='on_home_slide',
            new_name='on_home_slider',
        ),
    ]
