# Generated by Django 4.2.1 on 2023-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, upload_to='news/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
