# Generated by Django 4.2.1 on 2023-06-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gallery_embed_url_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='embed_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
