# Generated by Django 4.2.1 on 2023-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='appropriate',
            field=models.BooleanField(default=False),
        ),
    ]
